### ISSUE TITLE
Error installing dependencies

### ISSUE THREAD

**Issue by dianjuar** [worldsibu/convector-rest-api#13]
I cloned the repo, installed the dependencies with `npm install` and a wild error appears

![image](https://user-images.githubusercontent.com/7026066/66658811-df7dca80-ec07-11e9-87c3-9386ae22ba75.png)

**Comment by walmon** [comment]
Hi @dianjuar thanks for catching this. 

The project hasn't got any changes (as it's been stable) for the last few weeks, however `chain` a dependency had a breaking change without following the proper nomenclature so it's breaking some projects. 

In a nutshell, it's removing the `^` from the versions in the dependencies like this:

```
"mocha": "5.0.3",  
"chai": "4.1.2",  
"@types/mocha": "5.2.5",  
"@types/chai": "4.1.4"
```

You can modify it locally but if you'd like to drop a PR we'd be thankful! Otherwise, I'll push a fix later.

Also, to try the tool you don't need to clone the repo (so I imagine you wanted to do some changes to it) but if you'd only like to try it you can follow: https://www.npmjs.com/package/@worldsibu/conv-rest-api

**Comment by dianjuar** [comment]
Yes I'm trying to make some custom logic to your rest api generator, thats why I need the fork.

The error even doesn't let me compile :/

**Comment by dianjuar** [comment]
I made some test and discovered that the error is on chai types, so just a `"@types/chai": "~4.1.4"` will solve the error.

Is estrange that a minor version causes a breaking change

Expect my PR solving this
